#!/usr/bin/env node
/*
 * scripts/seed.mjs
 *
 * Reads the mock JSON fixtures under src/mock/ and emits a single SQL
 * file to drizzle/seed.sql containing INSERT statements for every
 * table the four screens read from. Then applies it to the local D1
 * via `wrangler d1 execute DB --local --env local --file=drizzle/seed.sql`.
 *
 * Idempotent: every insert is `INSERT OR REPLACE`, so re-running is safe.
 * Assumes migration 0000_initial.sql has already been applied.
 *
 * Usage:
 *   pnpm db:seed:local
 */

import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const mockDir = resolve(root, "src/mock");
const outDir = resolve(root, "drizzle");
mkdirSync(outDir, { recursive: true });
const outFile = resolve(outDir, "seed.sql");

/* ------------------------------ helpers ---------------------------- */

function readJson(name) {
  return JSON.parse(readFileSync(resolve(mockDir, name), "utf8"));
}

/** SQL-escape a JS value → literal, honouring null/booleans/numbers/strings. */
function lit(v) {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "boolean") return v ? "1" : "0";
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "NULL";
  const s = String(v).replaceAll("'", "''");
  return `'${s}'`;
}

const NOW = new Date().toISOString();

/** Concise short id for auto-keyed rows. */
let counter = 0;
function newId(prefix) {
  counter += 1;
  return `${prefix}_${String(counter).padStart(5, "0")}`;
}

/* ------------------------------ data ------------------------------- */

const leads = readJson("leads.json").filter(
  (l) => l.state !== "empty_workspace"
);
const properties = readJson("properties.json");
const comparables = readJson("comparables.json");
const agents = readJson("agents.json");
const agentCandidates = readJson("agent_candidates.json");
const outcomes = readJson("outcomes.json");
const activity = readJson("activity.json");

/*
 * Map from public lead id (e.g. "MTA-2026-00421") → internal PK we assign
 * for the row. Everything else that references a lead uses the internal id.
 */
const leadPkByPublic = new Map();
for (const lead of leads) {
  leadPkByPublic.set(lead.id, newId("lead"));
}

/*
 * Map from agent name → agent id, so lead_outcomes can back-fill
 * winning_agent_id when the mock referenced an agent by name.
 */
const agentIdByName = new Map();
for (const a of agents) {
  agentIdByName.set(a.name, a.id);
}

/* ------------------------------ SQL -------------------------------- */

const stmts = [];

stmts.push("-- Generated by scripts/seed.mjs — do not edit by hand.");
stmts.push("BEGIN TRANSACTION;");

// Users (2 sample rows so auth in step 3 has an allowlist to check against)
const sampleUsers = [
  {
    id: "user_sarah",
    email: "sarah@mytopagent.co.nz",
    name: "Sarah W.",
    role: "consultant",
  },
  {
    id: "user_admin",
    email: "sean@mytopagent.co.nz",
    name: "Sean McArthur",
    role: "admin",
  },
];
for (const u of sampleUsers) {
  stmts.push(
    `INSERT OR REPLACE INTO users (id, email, name, role, active, created_at) VALUES (${lit(u.id)}, ${lit(u.email)}, ${lit(u.name)}, ${lit(u.role)}, 1, ${lit(NOW)});`
  );
}

// Leads
for (const lead of leads) {
  const pk = leadPkByPublic.get(lead.id);
  const norm = lead.address.toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
  stmts.push(
    `INSERT OR REPLACE INTO leads (id, d1_lead_id, address_raw, address_normalised, vendor_name, phone, email, source, state, version, created_at, updated_at) VALUES (${lit(pk)}, ${lit(lead.id)}, ${lit(lead.address)}, ${lit(norm)}, ${lit(lead.vendor_name)}, ${lit(lead.phone)}, ${lit(lead.email)}, ${lit(lead.source)}, ${lit(lead.state)}, 1, ${lit(lead.created_at)}, ${lit(lead.created_at)});`
  );
}

// Properties (flatten per-field provenance into columns)
const propCols = [
  "cv",
  "land_value",
  "improvements",
  "estimate",
  "land_area",
  "floor_area",
  "bedrooms",
  "year_built",
  "last_sold_date",
  "last_sold_price",
];

for (const [publicId, facts] of Object.entries(properties)) {
  const pk = leadPkByPublic.get(publicId);
  if (!pk) continue;
  const values = ["lead_id"];
  const literals = [lit(pk)];
  for (const col of propCols) {
    const prov = facts[col];
    values.push(col, `${col}_source`, `${col}_fetched_at`);
    literals.push(
      lit(prov?.value ?? null),
      lit(prov?.source ?? null),
      lit(prov?.fetched_at ?? null)
    );
  }
  values.push("version", "updated_at");
  literals.push("1", lit(NOW));
  stmts.push(
    `INSERT OR REPLACE INTO properties (${values.join(", ")}) VALUES (${literals.join(", ")});`
  );
}

// Comparables
for (const [publicId, comps] of Object.entries(comparables)) {
  const pk = leadPkByPublic.get(publicId);
  if (!pk) continue;
  for (const c of comps) {
    stmts.push(
      `INSERT OR REPLACE INTO property_comparables (id, lead_id, address, sale_price, sale_date, distance_m, cv_at_sale, agent_name_raw, agency_raw, matched_agent_id, source, fetched_at) VALUES (${lit(newId("comp"))}, ${lit(pk)}, ${lit(c.address)}, ${lit(c.sale_price)}, ${lit(c.sale_date)}, ${lit(c.distance_m)}, ${lit(c.cv_at_sale)}, ${lit(c.agent_name)}, ${lit(c.agency)}, NULL, ${lit("mock")}, ${lit(NOW)});`
    );
  }
}

// Agents
for (const a of agents) {
  stmts.push(
    `INSERT OR REPLACE INTO agents (id, name, agency, phone, email, membership_status, sms_permission, sales_last_12mo, avg_days_on_market, nearby_sales, reason_hint, active, version, created_at, updated_at) VALUES (${lit(a.id)}, ${lit(a.name)}, ${lit(a.agency)}, ${lit(a.phone)}, ${lit(a.email)}, ${lit(a.membership_status)}, ${lit(a.sms_permission)}, ${lit(a.sales_last_12mo ?? 0)}, ${lit(a.avg_days_on_market ?? 0)}, ${lit(a.nearby_sales ?? 0)}, ${lit(a.reason_hint ?? null)}, 1, 1, ${lit(NOW)}, ${lit(NOW)});`
  );
}

// Candidates
for (const c of agentCandidates) {
  const pk = leadPkByPublic.get(c.first_seen_lead_id) ?? null;
  const nameNorm = c.name.toLowerCase();
  stmts.push(
    `INSERT OR REPLACE INTO agent_candidates (id, name_raw, name_normalised, agency, phone, email, source, first_seen_lead_id, match_agent_id, confidence, status, reason_hint, version, created_at, updated_at) VALUES (${lit(c.id)}, ${lit(c.name)}, ${lit(nameNorm)}, ${lit(c.agency)}, ${lit(c.phone)}, ${lit(c.email)}, ${lit("comparable")}, ${lit(pk)}, NULL, ${lit(c.confidence)}, ${lit("new")}, ${lit(c.reason_hint ?? null)}, 1, ${lit(NOW)}, ${lit(NOW)});`
  );
}

// Outcomes. The mock's outcomes.json references 30 lead ids but only a few
// have full lead records in leads.json — real-world outcomes span years of
// historical leads. For orphan references we insert a placeholder lead row
// (source=ac_import) so the FK holds and admin displays a realistic history.
for (const o of outcomes) {
  let pk = leadPkByPublic.get(o.lead_id);
  if (!pk) {
    pk = newId("lead");
    leadPkByPublic.set(o.lead_id, pk);
    stmts.push(
      `INSERT OR REPLACE INTO leads (id, d1_lead_id, address_raw, address_normalised, vendor_name, source, state, version, created_at, updated_at) VALUES (${lit(pk)}, ${lit(o.lead_id)}, ${lit("(historical AC lead)")}, ${lit("historical ac lead")}, ${lit("(historical)")}, ${lit("ac_import")}, ${lit("sold")}, 1, ${lit(o.recorded_at)}, ${lit(o.recorded_at)});`
    );
  }
  const winningAgentId = o.winning_agent
    ? agentIdByName.get(o.winning_agent) ?? null
    : null;
  stmts.push(
    `INSERT OR REPLACE INTO lead_outcomes (id, lead_id, outcome, winning_agent_id, winning_agent_name, sale_price, referral_amount, recorded_by, recorded_at, ac_synced_at) VALUES (${lit(newId("out"))}, ${lit(pk)}, ${lit(o.outcome)}, ${lit(winningAgentId)}, ${lit(o.winning_agent)}, ${lit(o.sale_price)}, ${lit(o.referral_amount)}, ${lit("seed")}, ${lit(o.recorded_at)}, NULL);`
  );
}

// Audit log rows synthesised from the mock activity per lead, so the
// workspace Timeline has content sourced from the real table.
for (const [publicId, events] of Object.entries(activity)) {
  const pk = leadPkByPublic.get(publicId);
  if (!pk) continue;
  for (const e of events) {
    const afterJson = JSON.stringify({ detail: e.detail });
    stmts.push(
      `INSERT OR REPLACE INTO audit_log (id, action, actor_user_id, entity_type, entity_id, lead_id, before_json, after_json, at) VALUES (${lit(newId("audit"))}, ${lit(e.type)}, NULL, ${lit("lead")}, ${lit(pk)}, ${lit(pk)}, NULL, ${lit(afterJson)}, ${lit(e.at)});`
    );
  }
}

stmts.push("COMMIT;");

writeFileSync(outFile, stmts.join("\n") + "\n", "utf8");
console.log(`Wrote ${stmts.length - 3} statements to ${outFile}`);

/* ------------------------- apply to local D1 ------------------------ */

console.log("Applying seed to local D1…");
execFileSync(
  "pnpm",
  [
    "wrangler",
    "d1",
    "execute",
    "DB",
    "--local",
    "--env",
    "local",
    `--file=${outFile}`,
  ],
  { cwd: root, stdio: "inherit" }
);
console.log("Seed complete.");
