#!/usr/bin/env node
/*
 * scripts/seed-staging.mjs
 *
 * Baseline seed for the *staging* D1 database. Deliberately narrow:
 *
 *   users             one admin (env-driven; default teaminsighter@)
 *   feature_flags     the six Phase-2/4/6 switches, all OFF
 *   template_versions two placeholder templates so the table isn't
 *                     empty (vendor + agent email v1 stubs)
 *   agents            all mock agents so the workspace shortlist has
 *                     content once real leads start flowing
 *   id_counters       lead_seq for the current UTC year, initialised
 *                     to 0 so the first ingested lead lands at NNNNN
 *                     = 00001
 *
 * No leads, no properties, no comparables, no candidates, no picks,
 * no outcomes, no audit_log — those must come from real webhook
 * traffic on staging, never from a seed.
 *
 * Usage:
 *   pnpm db:seed:staging
 *
 * Env overrides:
 *   SEED_ADMIN_EMAIL   default teaminsighter@gmail.com
 *   SEED_ADMIN_NAME    default "Imran Hossain"
 *
 * The script writes SQL to .wrangler/seed-staging.sql (gitignored)
 * and applies it with `wrangler d1 execute DB --remote --env staging
 * --file=.wrangler/seed-staging.sql`. Requires an authenticated
 * wrangler CLI on the target Cloudflare account.
 */

import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = resolve(__dirname, "..");
const mockDir = resolve(root, "src/mock");
const outDir = resolve(root, ".wrangler");
mkdirSync(outDir, { recursive: true });
const outFile = resolve(outDir, "seed-staging.sql");

function lit(v) {
  if (v === null || v === undefined) return "NULL";
  if (typeof v === "boolean") return v ? "1" : "0";
  if (typeof v === "number") return Number.isFinite(v) ? String(v) : "NULL";
  return `'${String(v).replaceAll("'", "''")}'`;
}

const NOW = new Date().toISOString();
const YEAR = new Date().getUTCFullYear();
const adminEmail = process.env.SEED_ADMIN_EMAIL ?? "teaminsighter@gmail.com";
const adminName = process.env.SEED_ADMIN_NAME ?? "Imran Hossain";

const stmts = [];
stmts.push("-- Generated by scripts/seed-staging.mjs — do not edit.");
stmts.push("BEGIN TRANSACTION;");

// -------------------- users --------------------
stmts.push(
  `INSERT OR REPLACE INTO users (id, email, name, role, active, created_at) VALUES (${lit(
    "user_bootstrap_admin"
  )}, ${lit(adminEmail)}, ${lit(adminName)}, ${lit("admin")}, 1, ${lit(NOW)});`
);

// -------------------- feature_flags --------------------
const flags = [
  ["cotality.enabled", false, "Cotality property adapter (Phase 4b)."],
  ["sync.ac_in_enabled", false, "AC webhook → D1 sync-in (Phase 2)."],
  ["sync.ac_out_enabled", false, "D1 → AC dispatcher outbound (Phase 2)."],
  ["sms.enabled", false, "TransmitSMS agent SMS channel (Phase 6)."],
  ["email.vendor_enabled", false, "Postmark vendor email (Phase 6)."],
  ["email.agent_enabled", false, "Postmark agent email (Phase 6)."],
];
for (const [name, enabled, notes] of flags) {
  stmts.push(
    `INSERT OR REPLACE INTO feature_flags (name, enabled, notes, updated_at) VALUES (${lit(
      name
    )}, ${lit(enabled)}, ${lit(notes)}, ${lit(NOW)});`
  );
}

// -------------------- system_health singleton --------------------
stmts.push(
  `INSERT OR REPLACE INTO system_health (id, last_cron_tick_at, last_reconciler_run_at, updated_at) VALUES ('singleton', NULL, NULL, ${lit(
    NOW
  )});`
);

// -------------------- template_versions --------------------
// Bare templates so Phase 6 has something to render and update. Bodies
// are placeholders; per §11 rule 6 real staging never emails a real
// recipient, only the allowlist. Every identifier used in {{ }} must
// resolve from lead/agent/vendor data at render time.
const templates = [
  {
    id: "tpl_vendor_email_v1",
    template_key: "vendor_email",
    version: 1,
    subject: "Your shortlist for {{lead.address}}",
    body:
      "Kia ora {{lead.vendor_name}},\n\n" +
      "Here are the agents we recommend for {{lead.address}}:\n" +
      "{{#agents}}\n- {{agent.name}} ({{agent.agency}}) — {{pick.reason_note}}\n{{/agents}}\n\n" +
      "Any of them will be in touch shortly.\n\n" +
      "— The MTA team",
  },
  {
    id: "tpl_agent_email_v1",
    template_key: "agent_email",
    version: 1,
    subject: "New listing lead in {{lead.suburb}}",
    body:
      "Hi {{agent.name}},\n\n" +
      "Vendor {{lead.vendor_name}} at {{lead.address}} is looking for an agent.\n" +
      "Please reply YES or NO by {{deadline}}.\n\n" +
      "— MTA",
  },
];
for (const t of templates) {
  stmts.push(
    `INSERT OR REPLACE INTO template_versions (id, template_key, version, subject, body, created_at) VALUES (${lit(
      t.id
    )}, ${lit(t.template_key)}, ${t.version}, ${lit(t.subject)}, ${lit(
      t.body
    )}, ${lit(NOW)});`
  );
}

// -------------------- agents --------------------
// Ships all 20 mock agents so the workspace shortlist has content the
// first time a real webhook lead lands. No leads, comparables, picks,
// or candidates are seeded — those come from real ingest traffic.
const agents = JSON.parse(
  readFileSync(resolve(mockDir, "agents.json"), "utf8")
);
for (const a of agents) {
  stmts.push(
    `INSERT OR REPLACE INTO agents (id, name, agency, phone, email, membership_status, sms_permission, sales_last_12mo, avg_days_on_market, nearby_sales, reason_hint, active, version, created_at, updated_at) VALUES (${lit(
      a.id
    )}, ${lit(a.name)}, ${lit(a.agency)}, ${lit(a.phone)}, ${lit(a.email)}, ${lit(
      a.membership_status
    )}, ${lit(a.sms_permission)}, ${lit(a.sales_last_12mo ?? 0)}, ${lit(
      a.avg_days_on_market ?? 0
    )}, ${lit(a.nearby_sales ?? 0)}, ${lit(
      a.reason_hint ?? null
    )}, 1, 1, ${lit(NOW)}, ${lit(NOW)});`
  );
}

// -------------------- id_counters --------------------
// First ingested lead on staging → MTA-<YEAR>-00001.
stmts.push(
  `INSERT OR REPLACE INTO id_counters (key, value, updated_at) VALUES (${lit(
    `lead_seq_${YEAR}`
  )}, 0, ${lit(NOW)});`
);

stmts.push("COMMIT;");

writeFileSync(outFile, stmts.join("\n") + "\n", "utf8");
console.log(`Wrote ${stmts.length - 3} statements to ${outFile}`);

// -------------------- apply --------------------
console.log("Applying seed to remote staging D1…");
execFileSync(
  "pnpm",
  [
    "wrangler",
    "d1",
    "execute",
    "DB",
    "--remote",
    "--env",
    "staging",
    `--file=${outFile}`,
  ],
  { cwd: root, stdio: "inherit" }
);
console.log("Staging seed complete.");
